### PR TITLE
Add dependencies(libboost and optional doxygen) to README

### PR DESCRIPTION
**Pull request by sanuj**
@linas For issue #22.

### CODE REVIEW

**Comment by linas** [comment]
Sorry I did not see this request. CircleCI serializes things .. can you do this:
```
git pull
git merge
git push
```
withtout that I cannot merge

**Comment by sanuj** [comment]
@linas Done.

**Comment by ngeiswei** [comment]
I believe there is an "Update Branch" button, near the "Merge pull request" button that saves one from pulling/pushing using the git commands. Very convenient!

**Comment by ngeiswei** [comment]
Thanks @sanuj

**Comment by sanuj** [comment]
Thanks for the info @ngeiswei I'll use it from the next time :)

**Pull request merged**
